from enum import IntEnum


# --- Major Event Types ---
class MajorEventType(IntEnum):
    """Major event types for Access Control events."""
    DEVICE_ALARM = 1
    DEVICE_EXCEPTION = 2
    DEVICE_OPERATION = 3
    DEVICE_EVENT = 5 # As per "5-Device Event" in documentation


# --- Minor Event Types per Major Type ---

class DeviceAlarmMinorType(IntEnum):
    """Minor event types for Device Alarm (Major Type 1)."""
    ZONE_SHORT_CIRCUIT_ATTEMPTS_ALARM = 1024
    ZONE_DISCONNECTED_ALARM = 1025
    ZONE_EXCEPTION_ALARM = 1026
    ZONE_RESTORED = 1027
    ZONE_TAMPERING_ALARM = 1028
    ZONE_TAMPERING_RESTORED = 1029
    CARD_READER_TAMPERING_ALARM = 1030
    CARD_READER_TAMPERING_RESTORED = 1031
    ALARM_INPUT_ALARM_TRIGGERED = 1032
    ALARM_INPUT_RESTORED = 1033
    DURESS_ALARM = 1034
    NO_MEMORY_FOR_OFFLINE_EVENT_STORAGE_ALARM = 1035
    MAXIMUM_FAILED_CARD_AUTHENTICATIONS_ALARM = 1036
    SD_CARD_FULL_ALARM = 1037
    CAPTURE_LINKAGE_ALARM = 1038
    SECURE_DOOR_CONTROL_UNIT_TAMPERING_ALARM = 1039
    SECURE_DOOR_CONTROL_UNIT_TAMPERING_RESTORED = 1040


class DeviceExceptionMinorType(IntEnum):
    """Minor event types for Device Exception (Major Type 2)."""
    NETWORK_DISCONNECTED = 39
    RS485_CONNECTION_EXCEPTION = 58
    RS485_CONNECTION_RESTORED = 59
    POWER_ON = 1024
    POWER_OFF = 1025
    WATCHDOG_RESET = 1026
    LOW_BATTERY_VOLTAGE = 1027
    BATTERY_VOLTAGE_RESTORED = 1028
    AC_POWER_DISCONNECTED = 1029
    AC_POWER_RESTORED = 1030
    NETWORK_RESTORED = 1031
    FLASH_READING_AND_WRITING_EXCEPTION = 1032
    CARD_READER_OFFLINE = 1033
    CARD_READER_ONLINE = 1034
    INDICATOR_TURNS_OFF = 1035
    INDICATOR_RESUMED = 1036
    LANE_CONTROLLER_OFFLINE = 1037
    LANE_CONTROLLER_ONLINE = 1038
    SECURE_DOOR_CONTROL_UNIT_OFFLINE = 1039
    SECURE_DOOR_CONTROL_UNIT_ONLINE = 1040
    ID_CARD_READER_DISCONNECTED = 1053
    ID_CARD_READER_CONNECTED = 1054
    FINGERPRINT_MODULE_DISCONNECTED = 1055
    FINGERPRINT_MODULE_CONNECTED = 1056
    CAMERA_DISCONNECTED = 1057
    CAMERA_CONNECTED = 1058
    COM_PORT_DISCONNECTED = 1059
    COM_PORT_CONNECTED = 1060
    DEVICE_UNAUTHORIZED = 1061
    FACE_RECOGNITION_TERMINAL_ONLINE = 1062
    FACE_RECOGNITION_TERMINAL_OFFLINE = 1063
    LOCAL_LOGIN_LOCK = 1064
    LOCAL_LOGIN_UNLOCK = 1065


class DeviceOperationMinorType(IntEnum):
    """Minor event types for Device Operation (Major Type 3)."""
    LOCAL_LOGIN = 80
    LOCAL_UPGRADE = 90
    REMOTE_LOGIN = 112
    REMOTE_LOGOUT = 113
    REMOTE_OPERATION_GET_PARAMETERS = 118
    REMOTE_OPERATION_SET_PARAMETERS = 119
    REMOTE_OPERATION_GET_STATUS = 120
    REMOTE_ARMING = 121
    REMOTE_DISARMING = 122
    REMOTE_REBOOT = 123
    REMOTE_UPGRADE = 126
    REMOTE_OPERATION_EXPORT_CONFIGURATION_FILE = 134
    REMOTE_OPERATION_IMPORT_CONFIGURATION_FILE = 135
    REMOTE_OPERATION_ENABLE_ALARM_OUTPUT_MANUALLY = 214
    REMOTE_OPERATION_DISABLE_ALARM_OUTPUT_MANUALLY = 215
    DOOR_REMOTELY_OPEN = 1024
    DOOR_REMOTELY_CLOSED = 1025
    REMAIN_OPEN_REMOTELY = 1026
    REMAIN_CLOSED_REMOTELY = 1027
    REMOTE_MANUAL_TIME_SYNC = 1028
    NETWORK_TIME_PROTOCOL_SYNCHRONIZATION = 1029
    REMOTE_OPERATION_CLEAR_ALL_CARD_NO = 1030
    REMOTE_OPERATION_RESTORE_DEFAULTS = 1031
    ZONE_ARMING = 1032
    ZONE_DISARMING = 1033
    LOCAL_OPERATION_RESTORE_DEFAULTS = 1034
    REMOTE_OPERATION_CAPTURE = 1035
    EDIT_NETWORK_PARAMETERS = 1036
    EDIT_GPRS_PARAMETERS = 1037
    EDIT_CONTROL_CENTER_PARAMETERS = 1038
    ENTER_DISMISS_CODE = 1039
    REMOTELY_ARMING = 1049
    REMOTELY_DISARMING = 1050
    M1_CARD_ENCRYPTION_VERIFICATION_ENABLED = 1055
    M1_CARD_ENCRYPTION_VERIFICATION_DISABLED = 1056
    OPENING_DOOR_WITH_NFC_CARD_ENABLED = 1057
    OPENING_DOOR_WITH_NFC_CARD_DISABLED = 1058


class DeviceEventMinorType(IntEnum):
    """Minor event types for Device Event (Major Type 5)."""
    VALID_CARD_AUTHENTICATION_COMPLETED = 1
    CARD_AND_PASSWORD_AUTHENTICATION_COMPLETED = 2
    CARD_AND_PASSWORD_AUTHENTICATION_FAILED = 3
    CARD_AND_PASSWORD_AUTHENTICATION_TIMED_OUT_4 = 4 # Renamed to avoid duplicate 5
    CARD_AND_PASSWORD_AUTHENTICATION_TIMED_OUT_5 = 5 # Renamed to differentiate
    NO_PERMISSION = 6
    INVALID_CARD_SWIPING_TIME_PERIOD = 7
    EXPIRED_CARD = 8
    CARD_NO_NOT_EXIST = 9
    ANTI_PASSING_BACK_AUTHENTICATION_FAILED = 10
    INTERLOCKING_DOOR_NOT_CLOSED = 11
    CARD_NOT_IN_MULTIPLE_AUTHENTICATION_GROUP = 12
    CARD_NOT_IN_MULTIPLE_AUTHENTICATION_DURATION = 13
    MULTIPLE_AUTHENTICATIONS_SUPER_PASSWORD_AUTHENTICATION_FAILED = 14
    MULTIPLE_AUTHENTICATION_COMPLETED = 15
    MULTIPLE_AUTHENTICATED = 16
    OPEN_DOOR_WITH_FIRST_CARD_STARTED = 17
    OPEN_DOOR_WITH_FIRST_CARD_STOPPED = 18
    REMAIN_OPEN_STARTED = 19
    REMAIN_OPEN_STOPPED = 20
    DOOR_UNLOCKED = 21
    DOOR_LOCKED = 22
    EXIT_BUTTON_PRESSED = 23
    EXIT_BUTTON_RELEASED = 24
    DOOR_OPEN_CONTACT = 25
    DOOR_CLOSED_CONTACT = 26
    DOOR_ABNORMALLY_OPEN_CONTACT = 27
    DOOR_OPEN_TIMED_OUT_CONTACT = 28
    ALARM_OUTPUT_ENABLED = 29
    ALARM_OUTPUT_DISABLED = 30
    REMAIN_CLOSED_STARTED = 31
    REMAIN_CLOSED_STOPPED = 32
    MULTIPLE_AUTHENTICATIONS_REMOTELY_OPEN_DOOR = 33
    MULTIPLE_AUTHENTICATIONS_SUPER_PASSWORD_AUTHENTICATION_COMPLETED = 34
    MULTIPLE_AUTHENTICATIONS_REPEATED_AUTHENTICATION = 35
    MULTIPLE_AUTHENTICATIONS_TIMED_OUT = 36
    DOORBELL_RING = 37
    FINGERPRINT_MATCHED = 38
    FINGERPRINT_MISMATCHED = 39
    CARD_AND_FINGERPRINT_AUTHENTICATION_COMPLETED = 40
    CARD_AND_FINGERPRINT_AUTHENTICATION_FAILED = 41
    CARD_AND_FINGERPRINT_AUTHENTICATION_TIMED_OUT = 42
    CARD_AND_FINGERPRINT_AND_PASSWORD_AUTHENTICATION_COMPLETED = 43
    CARD_AND_FINGERPRINT_AND_PASSWORD_AUTHENTICATION_FAILED = 44
    CARD_AND_FINGERPRINT_AND_PASSWORD_AUTHENTICATION_TIMED_OUT = 45
    FINGERPRINT_AND_PASSWORD_AUTHENTICATION_COMPLETED = 46
    FINGERPRINT_AND_PASSWORD_AUTHENTICATION_FAILED = 47
    FINGERPRINT_AND_PASSWORD_AUTHENTICATION_TIMED_OUT = 48
    FINGERPRINT_NOT_EXISTS = 49
    CARD_PLATFORM_AUTHENTICATION = 50
    CALL_CENTER = 51
    FACE_AND_FINGERPRINT_AUTHENTICATION_COMPLETED = 54
    FACE_AND_FINGERPRINT_AUTHENTICATION_FAILED = 55
    FACE_AND_FINGERPRINT_AUTHENTICATION_TIMED_OUT = 56
    FACE_AND_PASSWORD_AUTHENTICATION_COMPLETED = 57
    FACE_AND_PASSWORD_AUTHENTICATION_FAILED = 58
    FACE_AND_PASSWORD_AUTHENTICATION_TIMED_OUT = 59
    FACE_AND_CARD_AUTHENTICATION_COMPLETED = 60
    FACE_AND_CARD_AUTHENTICATION_FAILED = 61
    FACE_AND_CARD_AUTHENTICATION_TIMED_OUT = 62
    FACE_AND_PASSWORD_AND_FINGERPRINT_AUTHENTICATION_COMPLETED = 63
    FACE_AND_PASSWORD_AND_FINGERPRINT_AUTHENTICATION_FAILED = 64
    FACE_AND_PASSWORD_AND_FINGERPRINT_AUTHENTICATION_TIMED_OUT = 65
    FACE_AND_CARD_AND_FINGERPRINT_AUTHENTICATION_COMPLETED = 66
    FACE_AND_CARD_AND_FINGERPRINT_AUTHENTICATION_FAILED = 67
    FACE_AND_CARD_AND_FINGERPRINT_AUTHENTICATION_TIMED_OUT = 68
    EMPLOYEE_ID_AND_FINGERPRINT_AUTHENTICATION_COMPLETED = 69
    EMPLOYEE_ID_AND_FINGERPRINT_AUTHENTICATION_FAILED = 70
    EMPLOYEE_ID_AND_FINGERPRINT_AUTHENTICATION_TIMED_OUT = 71
    EMPLOYEE_ID_AND_FINGERPRINT_AND_PASSWORD_AUTHENTICATION_COMPLETED = 72
    EMPLOYEE_ID_AND_FINGERPRINT_AND_PASSWORD_AUTHENTICATION_FAILED = 73
    EMPLOYEE_ID_AND_FINGERPRINT_AND_PASSWORD_AUTHENTICATION_TIMED_OUT = 74
    FACE_AUTHENTICATION_COMPLETED = 75
    FACE_AUTHENTICATION_FAILED = 76
    EMPLOYEE_ID_AND_FACE_AUTHENTICATION_COMPLETED = 77
    EMPLOYEE_ID_AND_FACE_AUTHENTICATION_FAILED = 78
    EMPLOYEE_ID_AND_FACE_AUTHENTICATION_TIMED_OUT = 79
    FACE_RECOGNITION_FAILED = 80
    FIRST_CARD_AUTHORIZATION_STARTED = 81
    FIRST_CARD_AUTHORIZATION_ENDED = 82
    UNLOCKING_EXCEPTION = 92
    UNLOCKING_TIMED_OUT = 93
    EMPLOYEE_ID_AND_PASSWORD_AUTHENTICATION_COMPLETED = 101
    EMPLOYEE_ID_AND_PASSWORD_AUTHENTICATION_FAILED = 102
    EMPLOYEE_ID_AND_PASSWORD_AUTHENTICATION_TIMED_OUT = 103
    FACE_ANTI_SPOOFING_DETECTION_FAILED = 104
    FACE_AND_ID_CARD_AUTHENTICATED = 105
    FACE_AND_ID_CARD_AUTHENTICATION_FAILED = 112
    BLOCKLIST_EVENT = 113
    VALID_MESSAGE = 114
    INVALID_MESSAGE = 115
    MAC_DETECTION = 116
    M1_CARD_ENCRYPTION_VERIFICATION_FAILED = 119
    LOCAL_FACE_MODELING_FAILED = 142
    PASSWORD_AUTHENTICATION_FAILED_TIMES_EXCEEDED = 148
    PASSWORDS_MISMATCHED = 151
    EMPLOYEE_ID_NOT_EXISTS_152 = 152 # Note: duplicate value, renamed to differentiate
    COMBINED_AUTHENTICATION_COMPLETED = 153
    COMBINED_AUTHENTICATION_TIMED_OUT = 154
    AUTHENTICATION_TYPE_MISMATCHED = 155
    AUTHENTICATED_VIA_QR_CODE = 156
    AUTHENTICATION_VIA_OQ_CODE_FAILED = 157
    AUTHENTICATED_VIA_HOUSEHOLDER = 158
    AUTHENTICATED_VIA_BLUETOOTH = 159
    AUTHENTICATION_VIA_BLUETOOTH_FAILED = 160
    AUTHENTICATION_FAILED_INVALID_M1_CARD = 162
    VERIFYING_CPU_CARD_ENCRYPTION_FAILED = 163
    DISABLING_NFC_VERIFICATION_FAILED = 164
    EM_CARD_RECOGNITION_DISABLED = 168
    M1_CARD_RECOGNITION_DISABLED = 169
    CPU_CARD_RECOGNITION_DISABLED = 170
    ID_CARD_RECOGNITION_DISABLED = 171
    CARD_PASSWORD_FILLING_FAILED = 172
    LOCAL_UPGRADE_FAILED = 173
    REMOTE_UPGRADE_FAILED = 174
    REMOTE_UPGRADE_OF_EXTENSION_MODULE_COMPLETED = 175
    REMOTE_UPGRADE_OF_EXTENSION_MODULE_FAILED = 176
    REMOTE_UPGRADE_OF_FINGERPRINT_MODULE_COMPLETED = 177
    REMOTE_UPGRADE_OF_FINGERPRINT_MODULE_FAILED = 178
    DYNAMIC_VERIFICATION_CODE_VERIFIED = 179
    DYNAMIC_VERIFICATION_CODE_FAILED = 180
    PASSWORD_VERIFIED = 181
    CONSUMPTION_TIMED_OUT = 182
    ERROR_CORRECTION_TIMED_OUT = 183
    THE_MAXIMUM_SUM_OF_CONSUMPTION_REACHED = 184
    THE_MAXIMUM_TIMES_OF_CONSUMPTION_REACHED = 185
    CONSUMPTION_CONFIRMATION_TIMED_OUT = 186
    THE_MAXIMUM_NUMBER_OF_BLOCKLISTS_REACHED = 187
    DESFIRE_CARD_ENCRYPTION_AUTHENTICATION_FAILED = 188
    DESFIRE_CARD_RECOGNITION_DISABLED = 189
    IRIS_VERIFIED = 190
    IRIS_VERIFICATION_FAILED = 191
    IRIS_ANTI_SPOOFING_FAILED = 192
    PERCENTAGE_90_MAXIMUM_PERSONS_ALARM = 193 # Changed to PERCENTAGE_90_MAXIMUM_PERSONS_ALARM for clarity

